name: Build packages
on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * MON"
env:
  CACHIX_CACHE: capack
  # The name defined in https://github.com/nix-community/NUR/blob/master/repos.json
  REPO_NAME: kapack
jobs:
  build-packages:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh
          source ~/.nix-profile/etc/profile.d/nix.sh
          nix --version

  commit-push-on-nur:
    name: Commit and push on NUR branch
    runs-on: ubuntu-latest
    needs: build-packages
    if: success() && github.ref == 'refs/heads/commit-push-nur'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git identity
        run: |
          git config --global user.email "ci-bot@batsim.org"
          git config --global user.name "CI bot"
      - name: Revert previous autocommit on NUR
        run: |
          git checkout NUR
          git revert --no-edit HEAD
      - name: Merge commit-push-nur in NUR
        run: |
          git checkout NUR
          git merge --no-ff commit-push-nur -m '(auto) merge commit-push-nur in NUR'
      - name: Remove -master packages from default.nix
        run: sed -i -E 's/^[[:space:]]*([0-9A-Za-z\-]+\-master[[:space:]]*=.*)/# \1 \# automatically disabled for NUR/' default.nix
      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh
          source ~/.nix-profile/etc/profile.d/nix.sh
          nix --version
      - name: Make sure that default.nix is not ill-formed
        run: |
          source ~/.nix-profile/etc/profile.d/nix.sh
          nix eval --json -f ci.nix 'pkgs-to-build-with-deps'
      - name: Create commit (remove -master packages from default.nix)
        run: git commit -m '(auto) remove -master packages from default.nix' default.nix
      - name: Push NUR branch
        run: git push origin NUR
