name: Build packages
on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * MON"
env:
  CACHIX_CACHE: capack
  # The name defined in https://github.com/nix-community/NUR/blob/master/repos.json
  REPO_NAME: kapack
jobs:
  build-packages:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh
          source ~/.nix-profile/etc/profile.d/nix.sh
          nix --version
      - name: Set up cachix
        run: |
          source ~/.nix-profile/etc/profile.d/nix.sh
          nix-env -iA cachix -f https://cachix.org/api/v1/install
          cachix --version
          cachix use ${CACHIX_CACHE}
      - uses: actions/checkout@v2
      - name: Build packages
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        run: |
          source ~/.nix-profile/etc/profile.d/nix.sh
          nix run -f https://github.com/NixOS/nixpkgs/archive/20.09.tar.gz python3Packages.pytest --command pytest -ra -v --cachix-name=${CACHIX_CACHE} --push-deps-on-cachix --push-on-cachix --junit-xml pytest.xml
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test results
          path: pytest.xml

  publish-test-results:
    name: Publish test results
    runs-on: ubuntu-latest
    needs: build-packages
    if: success() || failure()
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml

  commit-push-on-nur:
    name: Commit and push on NUR branch
    runs-on: ubuntu-latest
    needs: build-packages
    if: success() && github.ref == 'refs/heads/commit-push-nur'
    steps:
      - name: Remove -master packages from default.nix
        run: sed -i -E 's/^[[:space:]]*([0-9A-Za-z\-]+\-master[[:space:]]*=.*)/# \1 # automatically disabled for NUR/' default.nix
      - name: Create commit
        run: git commit -m 'remove -master packages from default.nix (auto commit)'
      - name: Make NUR branch point on new commit
        run: git branch -f NUR HEAD
      - name: Push NUR branch
        run: git push origin NUR
